// This file was autogenerated by C:\Users\Carl Tessier\prog\clincqc\clincqc\scripts\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../app/options.js', ['clincqc.options'], []);
goog.addDependency('../../../app/ui/home.js', ['clincqc.ui.HomePanel'], ['goog.events', 'goog.ui.Button', 'goog.ui.Component']);
goog.addDependency('../../../app/ui/main.js', ['clincqc.ui'], ['clincqc.options', 'clincqc.ui.HomePanel', 'clincqc.ui.Map', 'clincqc.ui.PanelStack', 'goog.dom', 'goog.dom.ViewportSizeMonitor', 'goog.events', 'goog.events.EventType', 'goog.style', 'goog.ui.Component', 'goog.ui.SplitPane', 'goog.ui.SplitPane.Orientation']);
goog.addDependency('../../../app/ui/map.js', ['clincqc.ui.Map'], ['goog.events', 'goog.style', 'goog.ui.Component']);
goog.addDependency('../../../app/ui/panelstack.js', ['clincqc.ui.PanelStack'], ['goog.array', 'goog.events', 'goog.ui.Component']);
